### ISSUE TITLE
setup.py open() needs to be given a string path

### ISSUE THREAD

**Issue by naisanza** [utkonos/jreg#1]
As it is, setup seems to fail without it. 

https://github.com/utkonos/jreg/blob/master/setup.py#L20 : 
```
with open(here.joinpath('README.rst'), encoding='utf-8') as fh:
    long_description = fh.read()
```

working:
```
with open(str(here.joinpath('README.rst')), encoding='utf-8') as fh:
    long_description = fh.read()
```

**Comment by utkonos** [comment]
The `open` built in function should be able to handle pathlib objects in all operating systems, but it appears that linux has a different behavior. I will investigate, but conversion to string defeats the point of pathlib objects. Historically, pathlib has had problems with complete adoption across all parts of python. However, this was supposed to have been fixed with 3.6 as dabeaz mentions in his column from this past summer.
https://www.usenix.org/publications/login/summer2017/beazley

Either way, I will investigate when I have a moment.

**Comment by naisanza** [comment]
Yep it looked to be an old version issue. Closing

**Comment by utkonos** [comment]
I have specified the exact version of Python that this package is compatible with via PyPI classifiers in setup.py, but I will make an adjustment to the README to make it more clear that this is only compatible with 3.6. Thanks for the feedback!
